---
abstract: 'Perl extension for RocksDB'
author:
  - 'Jiro Nishiguchi <jiro@cpan.org>'
build_requires:
  ExtUtils::ParseXS: '0'
  Test::More: '0.98'
  Test::Warn: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RocksDB
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
    - vendor
provides:
  RocksDB:
    file: lib/RocksDB.pm
    version: '0.03'
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/spiritloose/RocksDB/issues
  homepage: https://github.com/spiritloose/RocksDB
  repository: git://github.com/spiritloose/RocksDB.git
version: '0.03'
